---
- name: Loop Example
  hosts: localhost
  gather_facts: false
  tasks:
    - name: loop example task
      debug:
        msg: "Watching {{ item }}"
      loop:
        - Netflix
        - Prime
        - Hotstar
