---
- name: Print the hostname of the Linux server
  hosts: all
  become: yes
  tasks:
    - name: Run echo command to display the hostname
      shell: echo "Hello! I am a Linux Server. My name is $HOSTNAME"
      register: result

    - name: Display the Result
      debug:
        var: result.stdout

    - name: Install chrony
      shell: dnf install chrony -y
      register: result_chrony

    - name: Display the Chrony Install Result
      debug:
        var: result_chrony.stdout

#ansible-playbook Playbook.yml -i inventory.yml --ask-become-pass