---
- name: Copy a file to a Windows host
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy a file
      win_copy:
        src: /home/utsav.tyagi/ChromeStandaloneSetup64.exe
        dest: C:\Temp\ChromeStandaloneSetup64.exe
        remote_src: false
      register: result

    - name: Display the Result
      debug:
        var: result