---
- name: Print the hostname of the Windows server
  hosts: all
  tasks:
    - name: Run echo command to display the hostname
      win_shell: echo "Hello! I am a Windows Server. My name is $(HOSTNAME)"
      register: result

    - name: Display the Result
      debug:
        var: result.stdout