---
- name: Variables from the command line
  hosts: all
  vars:
    var1: "stop"
    var2: "down"

  tasks:
    - name: Run when both conditions are true
      debug:
        msg: "Both Conditions Met"
      when: var1 == "stop" and var2 == "down"


    - name: Run when either condition is true
      debug:
        msg: "At Least One Condition Met"
      when: var1 == "stop" or  var2 == "down"