---
- name: Reboot Windows host
  hosts: all
  gather_facts: false
  tasks:
    - name: Reboot the server
      win_reboot:
        timeout: 600
      register: result

    - name: Display the Result
      debug:
        var: result